#pragma once

/** @file
 *  @brief Runtime-editable configuration, persisted in NVS.
 *
 *  Stored under the "geiger" NVS namespace. Missing keys fall back to
 *  compile-time defaults (DEF_* in config.c) so the device always boots
 *  with usable settings, even with a wiped NVS.
 */

#include <stdbool.h>
#include <stdint.h>
#include "esp_err.h"

typedef struct {
    // WiFi station credentials. Compile-time defaults cover first boot.
    char     wifi_ssid[33];
    char     wifi_password[65];

    // DHCP hostname (DHCP option 12 in the router lease table).
    // Empty = auto-filled at boot with "MultiGeiger<chip-id-decimal>"
    // (no hyphen — TP-Link DHCP silently drops DISCOVERs with hyphens).
    char     wifi_hostname[33];

    // AP-mode SSID broadcast during the 2-minute boot window and when no STA
    // credentials are configured. Empty = auto-filled at boot with
    // "esp32-<chip-id-decimal>".
    char     ap_name[33];

    // Radio capability limits applied to the STA interface before connect.
    //   wifi_11bg_only: disables 802.11n (radio falls back to 11b/g only).
    //   wifi_ht20_only: forces 20 MHz channel bandwidth (disables HT40).
    // Both default false = full capability. Compatibility knob for APs that
    // mishandle HT40 or 11n management frames.
    bool     wifi_11bg_only;
    bool     wifi_ht20_only;

    // When true, WiFi modem sleep is disabled (WIFI_PS_NONE). When false
    // (default), minimum modem sleep is used (WIFI_PS_MIN_MODEM), matching
    // the upstream MultiGeiger behaviour and reducing power draw slightly.
    bool     wifi_ps_disabled;

    // When true, route the WiFi RF chain to the u.FL external-antenna
    // connector (FeatherS3-D and similar boards with an onboard SPDT RF
    // switch). When false (default), the onboard PCB antenna is used.
    // No effect on boards without HAL_HAS_ANTENNA_SWITCH; the /config UI
    // greys the checkbox out in that case.
    bool     use_external_antenna;

    // Upload targets — per-target enable plus HTTPS toggle.
    bool     send_madavi;
    bool     madavi_https;
    bool     send_sensorc;
    bool     sensorc_https;
    bool     send_radmon;
    bool     radmon_https;
    char     radmon_user[33];
    char     radmon_password[65];

    // openSenseMap (https://opensensemap.org). One POST per cycle to
    // ingress.opensensemap.org/boxes/<BOX_ID>/data?luftdaten=1 carrying the
    // standard Luftdaten body — server picks up Si22G_*, BME280_* and SPS30_*
    // fields and writes them to the matching senseBox channels (channel ID
    // matching is configured per-box on the openSenseMap dashboard).
    // Always HTTPS (the http variant 301-redirects to https). Box IDs are
    // 24-char MongoDB ObjectId hex strings; field sized to 25 chars + null.
    bool     send_osm;
    char     osm_box_id[26];

    // openSenseMap access token (V2.3.16). Optional — when empty, uploads go
    // unauthenticated as they did pre-V2.3.16 (the Luftdaten compatibility
    // path historically accepted unauthenticated POSTs to a known box ID).
    // openSenseMap recently added an opt-in "require authentication" toggle
    // per-box on their dashboard — when enabled, unauthenticated POSTs are
    // rejected. Setting this token (generated under "Edit Box" → "Access
    // Token") and leaving the box's auth toggle on lets uploads continue
    // without disabling the box-side toggle. send_osm passes the token as
    // `Authorization: Bearer <token>` when non-empty. Token is a 64-char hex
    // string per OSM convention; field sized for 64 + null.
    char     osm_access_token[65];

    // aqi.eco (https://aqi.eco). POST to api.aqi.eco/update/<TOKEN> carrying
    // the same Luftdaten body wrapped with an esp8266id field at the top
    // (field name is legacy from the original airrohr fork — accepted for
    // ESP32-derived chip IDs too). Token is per-device, generated by the
    // user account on aqi.eco.
    bool     send_aqi;
    char     aqi_token[65];

    // Up to three NTP servers. Empty strings are skipped.
    char     ntp_server[64];
    char     ntp_server2[64];
    char     ntp_server3[64];

    // POSIX TZ string (see `man tzset`). Drives localtime() and strftime()
    // for log timestamps, the OLED time readout, and FTP upload filenames.
    // Examples:
    //   AEST-10AEDT,M10.1.0,M4.1.0/3   Sydney
    //   CET-1CEST,M3.5.0,M10.5.0/3     Germany
    //   UTC0                           UTC (no DST)
    char     tz_posix[48];

    // Web UI auth (user is always "admin"). Used by /config, /log and
    // /update. Default: ESP32Geiger.
    char     ap_password[33];

    // TX cycle interval (milliseconds).
    uint32_t tx_interval_ms;

    // Station altitude above sea level (metres). Used only to compute the
    // pressure-at-sealevel value sent to sensor.community.
    float    station_altitude_m;

    // When true, sensor.community receives pressure_sealevel in addition to
    // the raw pressure field. When false (default), the altitude-derived
    // value is omitted.
    bool     send_sealevel_pressure;

    // FTP log upload — periodically ships the in-memory log ring to a LAN
    // FTP server (e.g. router USB share). Passive mode.
    //   ftp_user/ftp_password empty = anonymous.
    //   ftp_host  : hostname or IPv4 address. Optional :port suffix (V2.3.16+)
    //               — if absent or malformed, defaults to FTP port 21.
    //               Example: "192.168.1.1" or "192.168.1.1:2121".
    //   ftp_path: remote directory; filename auto-generated as geiger_<chip>_<ts>.log.
    //   ftp_tls : explicit TLS (AUTH TLS on port 21). Certificate NOT verified
    //             (most LAN FTP servers use self-signed certs).
    bool     ftp_enabled;
    bool     ftp_tls;
    char     ftp_host[64];
    char     ftp_user[33];
    char     ftp_password[65];
    char     ftp_path[64];
    uint32_t ftp_interval_min;

    // When true, WiFi modem sleep is forced off for the duration of each FTP
    // transfer and restored to WIFI_PS_MIN_MODEM at the end. Workaround for
    // boards where DTIM-delayed TCP ACKs stall FTPS uploads (observed on the
    // older sensor with degraded WiFi RX). Default false — newer boards do
    // not need it. Has no effect when wifi_ps_disabled is true (radio is
    // already always-on); the /config UI greys this box out in that case.
    bool     ftp_ps_disabled;

    // When true (default in V2.3.15), FTPS handshakes are capped at TLS 1.2
    // (mbedtls_ssl_conf_max_tls_version). V2.3.15 bench testing confirmed
    // TLS 1.3 fails with "426 Connection reset by peer" on the data channel
    // against the project's LAN FTPS server — independent of session reuse.
    // TLS 1.2 + ctrl-session reuse on data is the known-working combination.
    // Untick the /config checkbox to allow TLS 1.3 (works against modern
    // cloud TLS terminators; YMMV on older / embedded FTPS daemons). HTTPS
    // targets (Madavi / SC / Radmon / OSM / aqi.eco) are unaffected — they
    // always negotiate 1.3 freely via esp_tls (separate code path). See
    // reference_ftps_tls13_investigation.md memory for full background.
    bool     ftp_tls12_only;

    // User-facing feedback knobs.
    //   speaker_tick: piezo click on every counted GM pulse.
    //   led_tick    : onboard LED flash on every counted GM pulse.
    //   play_sound  : short boot chirp confirming the speaker is wired up.
    //   show_display: drive the OLED (boot splash + running stats).
    bool     speaker_tick;
    bool     led_tick;
    bool     play_sound;
    bool     show_display;

    // When false, the Geiger subsystem is fully disabled at boot:
    //   - tube_setup() skips ISR install, HV gptimer and HV charge-pump GPIOs
    //     (HV_FET is driven LOW so the boost MOSFET stays off, but no
    //     recharge cycles run and no edge interrupts fire).
    //   - tube_read() returns zero counts / dt_ms / hv_pulses.
    //   - Radiation upload paths are skipped (Madavi geiger POST, sensor.community
    //     X-PIN 19 POST, and Radmon entirely). Madavi/SC THP paths still run if
    //     an env sensor is present.
    // Default true — preserves the original Geiger-counter behaviour when
    // upgrading from V2.2.x. Toggle requires reboot (config_post sets the
    // restart flag automatically).
    bool     tube_enabled;
} config_t;

/** @brief Fill cfg with compile-time defaults. Always safe to call. */
void config_defaults(config_t *cfg);

/** @brief Load from NVS, falling back to defaults for missing keys.
 *
 *  Never fails — unrecoverable NVS issues just leave cfg at defaults.
 */
void config_load(config_t *cfg);

/** @brief Persist cfg to NVS. Returns esp_err from nvs_commit. */
esp_err_t config_save(const config_t *cfg);
